# Generated by Django 5.2.6 on 2025-09-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='vip_mode',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
