# Generated by Django 5.2.6 on 2025-09-30 03:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('player_count', models.IntegerField()),
                ('server_version', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField()),
                ('vip_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
