# Generated by Django 5.2.6 on 2025-10-01 03:10

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('serverstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatus',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Server Status',
                'verbose_name_plural': 'Server Status',
            },
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
