# Generated by Django 5.2.6 on 2025-09-30 03:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('market', '0001_market_group_with_types_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroupWithTypes',
            fields=[
                (
                    'market_group_id',
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ('market_group_name', models.CharField(max_length=255)),
                ('parent_group_id', models.IntegerField(null=True)),
                ('type_id', models.IntegerField(null=True)),
                ('type_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'market_group_with_types',
                'managed': False,
            },
        ),
    ]
