# Generated by Django 5.2.6 on 2025-10-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('build_number', models.IntegerField(primary_key=True, serialize=False)),
                ('change_date', models.DateField()),
                ('file_changes', models.JSONField(default=dict)),
                ('field_changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'Changelogs',
                'ordering': ['-build_number'],
            },
        ),
    ]
