# Generated by Django 5.2.6 on 2025-09-23 04:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Checksum',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('checksum', models.CharField(max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
