# Generated by Django 5.2.6 on 2025-09-30 04:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('sde', '0002_initial_model_gen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='type',
            index=models.Index(
                fields=['market_group_id'], name='sde_type_market__9297cf_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='type',
            index=models.Index(fields=['group_id'], name='sde_type_group_i_7c00ca_idx'),
        ),
    ]
