# Generated by Django 5.2.6 on 2025-09-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0002_initial_generator_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksum',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
