# Generated by Django 5.2.6 on 2025-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared', models.DateTimeField()),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('mutual', models.BooleanField()),
                ('open_for_allies', models.BooleanField()),
                ('retracted', models.DateTimeField(null=True)),
                ('aggressor', models.JSONField()),
                ('allies', models.JSONField()),
                ('defender', models.JSONField()),
            ],
        ),
    ]
