# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class AgentsInSpace(models.Model):
    dungeon_id = models.IntegerField()
    solar_system_id = models.IntegerField()
    spawn_point_id = models.IntegerField()
    type_id = models.IntegerField()
