# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class AgentsInSpace(models.Model):
    id = models.BigIntegerField(primary_key=True)
    dungeon_id = models.IntegerField()
    solar_system_id = models.IntegerField()
    spawn_point_id = models.IntegerField()
    type_id = models.IntegerField()

    class Meta:
        verbose_name = 'Agents In Space'
        verbose_name_plural = 'Agents In Spaces'

    def __str__(self):
        return f'AgentsInSpace: {self.id}'
