# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class AgentType(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.TextField()

    class Meta:
        verbose_name = 'Agent Type'
        verbose_name_plural = 'Agent Types'

    def __str__(self):
        return f'AgentType: {self.id}'
