# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class Agent(models.Model):
    agent_type_id = models.IntegerField()
    corporation_id = models.IntegerField()
    division_id = models.IntegerField()
    is_locator = models.BooleanField()
    level = models.IntegerField()
    location_id = models.IntegerField()
