# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class Ancestry(models.Model):
    bloodline_id = models.IntegerField()
    charisma = models.IntegerField()
    description_id = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    intelligence = models.IntegerField()
    memory = models.IntegerField()
    name_id = models.JSONField()
    perception = models.IntegerField()
    short_description = models.TextField(default=None, null=True)
    willpower = models.IntegerField()
