# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Ancestry(models.Model):
    id = models.BigIntegerField(primary_key=True)
    bloodline_id = models.IntegerField()
    charisma = models.IntegerField()
    description = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    intelligence = models.IntegerField()
    memory = models.IntegerField()
    name = models.JSONField()
    perception = models.IntegerField()
    short_description = models.TextField(default=None, null=True)
    willpower = models.IntegerField()

    class Meta:
        verbose_name = 'Ancestry'
        verbose_name_plural = 'Ancestrys'

    def __str__(self):
        return f'Ancestry: {self.id}'
