# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class AsteroidBelt(models.Model):
    position = models.JSONField()
    statistics = models.JSONField(default=dict, null=True)
    type_id = models.IntegerField()
    asteroid_belt_name_id = models.IntegerField(default=None, null=True)
