# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Bloodline(models.Model):
    charisma = models.IntegerField()
    corporation_id = models.IntegerField()
    description_id = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    intelligence = models.IntegerField()
    memory = models.IntegerField()
    name_id = models.JSONField()
    perception = models.IntegerField()
    race_id = models.IntegerField()
    willpower = models.IntegerField()
