# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Bloodline(models.Model):
    id = models.BigIntegerField(primary_key=True)
    charisma = models.IntegerField()
    corporation_id = models.IntegerField()
    description = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    intelligence = models.IntegerField()
    memory = models.IntegerField()
    name = models.JSONField()
    perception = models.IntegerField()
    race_id = models.IntegerField()
    willpower = models.IntegerField()

    class Meta:
        verbose_name = 'Bloodline'
        verbose_name_plural = 'Bloodlines'

    def __str__(self):
        return f'Bloodline: {self.id}'
