# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Blueprint(models.Model):
    id = models.BigIntegerField(primary_key=True)
    activities = models.JSONField()
    blueprint_type_id = models.IntegerField()
    max_production_limit = models.IntegerField()

    class Meta:
        verbose_name = 'Blueprint'
        verbose_name_plural = 'Blueprints'

    def __str__(self):
        return f'Blueprint: {self.id}'
