# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Blueprint(models.Model):
    activities = models.JSONField()
    blueprint_type_id = models.IntegerField()
    max_production_limit = models.IntegerField()
