# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class Category(models.Model):
    name = models.JSONField()
    published = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)
