# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Category(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.JSONField()
    published = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'

    def __str__(self):
        return f'Category: {self.id}'
