# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class Certificate(models.Model):
    description = models.TextField()
    group_id = models.IntegerField()
    name = models.TextField()
    recommended_for = models.JSONField(default=list, null=True)
    skill_types = models.JSONField()
