# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Certificate(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.JSONField()
    group_id = models.IntegerField()
    name = models.JSONField()
    recommended_for = models.JSONField(default=list, null=True)
    skill_types = models.JSONField()

    class Meta:
        verbose_name = 'Certificate'
        verbose_name_plural = 'Certificates'

    def __str__(self):
        return f'Certificate: {self.id}'
