# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class CharacterAttribute(models.Model):
    description = models.TextField()
    icon_id = models.IntegerField()
    name_id = models.JSONField()
    notes = models.TextField()
    short_description = models.TextField()
