# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class CharacterAttribute(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.TextField()
    icon_id = models.IntegerField()
    name = models.JSONField()
    notes = models.TextField()
    short_description = models.TextField()

    class Meta:
        verbose_name = 'Character Attribute'
        verbose_name_plural = 'Character Attributes'

    def __str__(self):
        return f'CharacterAttribute: {self.id}'
