# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Constellation(models.Model):
    center = models.JSONField()
    constellation_id = models.IntegerField(primary_key=True)
    max = models.JSONField()
    min = models.JSONField()
    name_id = models.IntegerField()
    radius = models.FloatField()
    faction_id = models.IntegerField(default=None, null=True)
    wormhole_class_id = models.IntegerField(default=None, null=True)
