# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class ControlTowerResource(models.Model):
    id = models.BigIntegerField(primary_key=True)
    resources = models.JSONField()

    class Meta:
        verbose_name = 'Control Tower Resource'
        verbose_name_plural = 'Control Tower Resources'

    def __str__(self):
        return f'ControlTowerResource: {self.id}'
