# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class ContrabandType(models.Model):
    id = models.BigIntegerField(primary_key=True)
    factions = models.JSONField()

    class Meta:
        verbose_name = 'Contraband Type'
        verbose_name_plural = 'Contraband Types'

    def __str__(self):
        return f'ContrabandType: {self.id}'
