# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class CorporationActivity(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.JSONField()

    class Meta:
        verbose_name = 'Corporation Activity'
        verbose_name_plural = 'Corporation Activitys'

    def __str__(self):
        return f'CorporationActivity: {self.id}'
