# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class CorporationActivity(models.Model):
    name_id = models.JSONField()
