# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DbuffCollection(models.Model):
    id = models.BigIntegerField(primary_key=True)
    aggregate_mode = models.TextField()
    developer_description = models.TextField()
    item_modifiers = models.JSONField(default=list, null=True)
    location_group_modifiers = models.JSONField(default=list, null=True)
    location_modifiers = models.JSONField(default=list, null=True)
    location_required_skill_modifiers = models.JSONField(default=list, null=True)
    operation_name = models.TextField()
    show_output_value_in_ui = models.TextField()
    display_name = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Dbuff Collection'
        verbose_name_plural = 'Dbuff Collections'

    def __str__(self):
        return f'DbuffCollection: {self.id}'
