# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DogmaAttribute(models.Model):
    id = models.BigIntegerField(primary_key=True)
    attribute_category_id = models.IntegerField(default=None, null=True)
    data_type = models.IntegerField()
    default_value = models.DecimalField(max_digits=50, decimal_places=30)
    description = models.TextField(default=None, null=True)
    display_when_zero = models.BooleanField()
    high_is_good = models.BooleanField()
    name = models.TextField()
    published = models.BooleanField()
    stackable = models.BooleanField()
    display_name = models.JSONField(default=dict, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    tooltip_description = models.JSONField(default=dict, null=True)
    tooltip_title = models.JSONField(default=dict, null=True)
    unit_id = models.IntegerField(default=None, null=True)
    charge_recharge_time_id = models.IntegerField(default=None, null=True)
    max_attribute_id = models.IntegerField(default=None, null=True)
    min_attribute_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Dogma Attribute'
        verbose_name_plural = 'Dogma Attributes'

    def __str__(self):
        return f'DogmaAttribute: {self.id}'
