# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DogmaEffect(models.Model):
    id = models.BigIntegerField(primary_key=True)
    disallow_auto_repeat = models.BooleanField()
    discharge_attribute_id = models.IntegerField(default=None, null=True)
    duration_attribute_id = models.IntegerField(default=None, null=True)
    effect_category_id = models.IntegerField()
    electronic_chance = models.BooleanField()
    guid = models.TextField(default=None, null=True)
    is_assistance = models.BooleanField()
    is_offensive = models.BooleanField()
    is_warp_safe = models.BooleanField()
    name = models.TextField()
    propulsion_chance = models.BooleanField()
    published = models.BooleanField()
    range_chance = models.BooleanField()
    distribution = models.IntegerField(default=None, null=True)
    falloff_attribute_id = models.IntegerField(default=None, null=True)
    range_attribute_id = models.IntegerField(default=None, null=True)
    tracking_speed_attribute_id = models.IntegerField(default=None, null=True)
    description = models.JSONField(default=dict, null=True)
    display_name = models.JSONField(default=dict, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    modifier_info = models.JSONField(default=list, null=True)
    npc_usage_chance_attribute_id = models.IntegerField(default=None, null=True)
    npc_activation_chance_attribute_id = models.IntegerField(default=None, null=True)
    fitting_usage_chance_attribute_id = models.IntegerField(default=None, null=True)
    resistance_attribute_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Dogma Effect'
        verbose_name_plural = 'Dogma Effects'

    def __str__(self):
        return f'DogmaEffect: {self.id}'
