# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DogmaAttributeCategory(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.TextField(default=None, null=True)
    name = models.TextField()

    class Meta:
        verbose_name = 'Dogma Attribute Category'
        verbose_name_plural = 'Dogma Attribute Categorys'

    def __str__(self):
        return f'DogmaAttributeCategory: {self.id}'
