# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DogmaUnit(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.JSONField(default=dict, null=True)
    display_name = models.JSONField(default=dict, null=True)
    name = models.TextField()

    class Meta:
        verbose_name = 'Dogma Unit'
        verbose_name_plural = 'Dogma Units'

    def __str__(self):
        return f'DogmaUnit: {self.id}'
