# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class DynamicItemAttribute(models.Model):
    id = models.BigIntegerField(primary_key=True)
    attribute_ids = models.JSONField()
    input_output_mapping = models.JSONField()

    class Meta:
        verbose_name = 'Dynamic Item Attribute'
        verbose_name_plural = 'Dynamic Item Attributes'

    def __str__(self):
        return f'DynamicItemAttribute: {self.id}'
