# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Faction(models.Model):
    id = models.BigIntegerField(primary_key=True)
    corporation_id = models.IntegerField(default=None, null=True)
    description = models.JSONField()
    flat_logo = models.TextField(default=None, null=True)
    flat_logo_with_name = models.TextField(default=None, null=True)
    icon_id = models.IntegerField()
    member_races = models.JSONField()
    militia_corporation_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    short_description = models.JSONField(default=dict, null=True)
    size_factor = models.DecimalField(max_digits=50, decimal_places=30)
    solar_system_id = models.IntegerField()
    unique_name = models.BooleanField()

    class Meta:
        verbose_name = 'Faction'
        verbose_name_plural = 'Factions'

    def __str__(self):
        return f'Faction: {self.id}'
