# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Graphic(models.Model):
    id = models.BigIntegerField(primary_key=True)
    graphic_file = models.TextField(default=None, null=True)
    icon_folder = models.TextField(default=None, null=True)
    sof_faction_name = models.TextField(default=None, null=True)
    sof_hull_name = models.TextField(default=None, null=True)
    sof_race_name = models.TextField(default=None, null=True)
    sof_material_set_id = models.IntegerField(default=None, null=True)
    sof_layout = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Graphic'
        verbose_name_plural = 'Graphics'

    def __str__(self):
        return f'Graphic: {self.id}'
