# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class GraphicId(models.Model):
    description = models.TextField(default=None, null=True)
    graphic_file = models.TextField(default=None, null=True)
    icon_info = models.JSONField(default=dict, null=True)
    sof_faction_name = models.TextField(default=None, null=True)
    sof_hull_name = models.TextField(default=None, null=True)
    sof_race_name = models.TextField(default=None, null=True)
    sof_layout = models.JSONField(default=list, null=True)
