# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Group(models.Model):
    id = models.BigIntegerField(primary_key=True)
    anchorable = models.BooleanField()
    anchored = models.BooleanField()
    category_id = models.IntegerField()
    fittable_non_singleton = models.BooleanField()
    name = models.JSONField()
    published = models.BooleanField()
    use_base_price = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

    def __str__(self):
        return f'Group: {self.id}'
