# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Group(models.Model):
    anchorable = models.BooleanField()
    anchored = models.BooleanField()
    category_id = models.IntegerField()
    fittable_non_singleton = models.BooleanField()
    name = models.JSONField()
    published = models.BooleanField()
    use_base_price = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)
