# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Icon(models.Model):
    id = models.BigIntegerField(primary_key=True)
    icon_file = models.TextField()

    class Meta:
        verbose_name = 'Icon'
        verbose_name_plural = 'Icons'

    def __str__(self):
        return f'Icon: {self.id}'
