# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class IconId(models.Model):
    description = models.TextField(default=None, null=True)
    icon_file = models.TextField()
    obsolete = models.BooleanField(default=False, null=True)
