# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class InvUniqueName(models.Model):
    group_id = models.IntegerField()
    item_id = models.IntegerField(primary_key=True)
    item_name = models.TextField()
