# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class InvFlag(models.Model):
    flag_id = models.IntegerField(primary_key=True)
    flag_name = models.TextField()
    flag_text = models.TextField()
    order_id = models.IntegerField()
