# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Landmark(models.Model):
    description_id = models.IntegerField()
    landmark_name_id = models.IntegerField()
    position = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    location_id = models.IntegerField(default=None, null=True)
