# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Landmark(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.JSONField()
    name = models.JSONField()
    position = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    location_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Landmark'
        verbose_name_plural = 'Landmarks'

    def __str__(self):
        return f'Landmark: {self.id}'
