# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapRegion(models.Model):
    id = models.BigIntegerField(primary_key=True)
    constellation_ids = models.JSONField()
    description = models.JSONField(default=dict, null=True)
    faction_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    nebula_id = models.IntegerField()
    position = models.JSONField()
    wormhole_class_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Map Region'
        verbose_name_plural = 'Map Regions'

    def __str__(self):
        return f'MapRegion: {self.id}'
