# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapStargate(models.Model):
    id = models.BigIntegerField(primary_key=True)
    destination = models.JSONField()
    position = models.JSONField()
    solar_system_id = models.IntegerField()
    type_id = models.IntegerField()

    class Meta:
        verbose_name = 'Map Stargate'
        verbose_name_plural = 'Map Stargates'

    def __str__(self):
        return f'MapStargate: {self.id}'
