# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapPlanet(models.Model):
    id = models.BigIntegerField(primary_key=True)
    asteroid_belt_ids = models.JSONField(default=list, null=True)
    attributes = models.JSONField()
    celestial_index = models.IntegerField()
    moon_ids = models.JSONField(default=list, null=True)
    orbit_id = models.IntegerField()
    position = models.JSONField()
    radius = models.IntegerField()
    solar_system_id = models.IntegerField()
    statistics = models.JSONField()
    type_id = models.IntegerField()
    npc_station_ids = models.JSONField(default=list, null=True)
    unique_name = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Map Planet'
        verbose_name_plural = 'Map Planets'

    def __str__(self):
        return f'MapPlanet: {self.id}'
