# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapMoon(models.Model):
    id = models.BigIntegerField(primary_key=True)
    attributes = models.JSONField()
    celestial_index = models.IntegerField()
    orbit_id = models.IntegerField()
    orbit_index = models.IntegerField()
    position = models.JSONField()
    radius = models.DecimalField(max_digits=50, decimal_places=30)
    solar_system_id = models.IntegerField()
    statistics = models.JSONField(default=dict, null=True)
    type_id = models.IntegerField()
    npc_station_ids = models.JSONField(default=list, null=True)
    unique_name = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Map Moon'
        verbose_name_plural = 'Map Moons'

    def __str__(self):
        return f'MapMoon: {self.id}'
