# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapAsteroidBelt(models.Model):
    id = models.BigIntegerField(primary_key=True)
    celestial_index = models.IntegerField()
    orbit_id = models.IntegerField()
    orbit_index = models.IntegerField()
    position = models.JSONField()
    radius = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    solar_system_id = models.IntegerField()
    statistics = models.JSONField(default=dict, null=True)
    type_id = models.IntegerField()
    unique_name = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Map Asteroid Belt'
        verbose_name_plural = 'Map Asteroid Belts'

    def __str__(self):
        return f'MapAsteroidBelt: {self.id}'
