# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapConstellation(models.Model):
    id = models.BigIntegerField(primary_key=True)
    faction_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    position = models.JSONField()
    region_id = models.IntegerField()
    solar_system_ids = models.JSONField()
    wormhole_class_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Map Constellation'
        verbose_name_plural = 'Map Constellations'

    def __str__(self):
        return f'MapConstellation: {self.id}'
