# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapSolarSystem(models.Model):
    id = models.BigIntegerField(primary_key=True)
    border = models.BooleanField(default=False, null=True)
    constellation_id = models.IntegerField()
    hub = models.BooleanField(default=False, null=True)
    international = models.BooleanField(default=False, null=True)
    luminosity = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    name = models.JSONField()
    planet_ids = models.JSONField(default=list, null=True)
    position = models.JSONField()
    radius = models.DecimalField(max_digits=50, decimal_places=30)
    region_id = models.IntegerField()
    regional = models.BooleanField(default=False, null=True)
    security_class = models.TextField(default=None, null=True)
    security_status = models.DecimalField(max_digits=50, decimal_places=30)
    star_id = models.IntegerField(default=None, null=True)
    stargate_ids = models.JSONField(default=list, null=True)
    corridor = models.BooleanField(default=False, null=True)
    fringe = models.BooleanField(default=False, null=True)
    wormhole_class_id = models.IntegerField(default=None, null=True)
    visual_effect = models.TextField(default=None, null=True)
    disallowed_anchor_categories = models.JSONField(default=list, null=True)
    disallowed_anchor_groups = models.JSONField(default=list, null=True)
    faction_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Map Solar System'
        verbose_name_plural = 'Map Solar Systems'

    def __str__(self):
        return f'MapSolarSystem: {self.id}'
