# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MapStar(models.Model):
    id = models.BigIntegerField(primary_key=True)
    radius = models.BigIntegerField()
    solar_system_id = models.IntegerField()
    statistics = models.JSONField()
    type_id = models.IntegerField()

    class Meta:
        verbose_name = 'Map Star'
        verbose_name_plural = 'Map Stars'

    def __str__(self):
        return f'MapStar: {self.id}'
