# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class MarketGroup(models.Model):
    description_id = models.JSONField(default=dict, null=True)
    has_types = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)
    name_id = models.JSONField()
    parent_group_id = models.IntegerField(default=None, null=True)
