# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MarketGroup(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.JSONField(default=dict, null=True)
    has_types = models.BooleanField()
    icon_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    parent_group_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Market Group'
        verbose_name_plural = 'Market Groups'

    def __str__(self):
        return f'MarketGroup: {self.id}'
