# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class MetaGroup(models.Model):
    id = models.BigIntegerField(primary_key=True)
    color = models.JSONField(default=dict, null=True)
    name = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    icon_suffix = models.TextField(default=None, null=True)
    description = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Meta Group'
        verbose_name_plural = 'Meta Groups'

    def __str__(self):
        return f'MetaGroup: {self.id}'
