# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class MetaGroup(models.Model):
    color = models.JSONField(default=list, null=True)
    name_id = models.JSONField()
    icon_id = models.IntegerField(default=None, null=True)
    icon_suffix = models.TextField(default=None)
    description_id = models.JSONField(default=dict, null=True)
