# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Moon(models.Model):
    planet_attributes = models.JSONField()
    position = models.JSONField()
    radius = models.IntegerField()
    statistics = models.JSONField(default=dict, null=True)
    type_id = models.IntegerField()
    npc_stations = models.JSONField(default=dict, null=True)
    moon_name_id = models.IntegerField(default=None, null=True)
