# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class NpcCorporationDivision(models.Model):
    id = models.BigIntegerField(primary_key=True)
    display_name = models.TextField(default=None, null=True)
    internal_name = models.TextField()
    leader_type_name = models.JSONField()
    name = models.JSONField()
    description = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Npc Corporation Division'
        verbose_name_plural = 'Npc Corporation Divisions'

    def __str__(self):
        return f'NpcCorporationDivision: {self.id}'
