# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class NpcCorporationDivision(models.Model):
    description = models.TextField(default=None, null=True)
    internal_name = models.TextField()
    leader_type_name_id = models.JSONField()
    name_id = models.JSONField()
    description_id = models.JSONField(default=dict, null=True)
