# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class NpcStation(models.Model):
    id = models.BigIntegerField(primary_key=True)
    celestial_index = models.IntegerField(default=None, null=True)
    operation_id = models.IntegerField()
    orbit_id = models.IntegerField()
    orbit_index = models.IntegerField(default=None, null=True)
    owner_id = models.IntegerField()
    position = models.JSONField()
    reprocessing_efficiency = models.DecimalField(max_digits=50, decimal_places=30)
    reprocessing_hangar_flag = models.IntegerField()
    reprocessing_stations_take = models.DecimalField(max_digits=50, decimal_places=30)
    solar_system_id = models.IntegerField()
    type_id = models.IntegerField()
    use_operation_name = models.BooleanField()

    class Meta:
        verbose_name = 'Npc Station'
        verbose_name_plural = 'Npc Stations'

    def __str__(self):
        return f'NpcStation: {self.id}'
