# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class NpcCharacter(models.Model):
    id = models.BigIntegerField(primary_key=True)
    bloodline_id = models.IntegerField()
    ceo = models.BooleanField()
    corporation_id = models.IntegerField()
    gender = models.BooleanField()
    location_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    race_id = models.IntegerField()
    start_date = models.TextField(default=None, null=True)
    unique_name = models.BooleanField()
    skills = models.JSONField(default=list, null=True)
    ancestry_id = models.IntegerField(default=None, null=True)
    career_id = models.IntegerField(default=None, null=True)
    school_id = models.IntegerField(default=None, null=True)
    speciality_id = models.IntegerField(default=None, null=True)
    agent = models.JSONField(default=dict, null=True)
    description = models.TextField(default=None, null=True)

    class Meta:
        verbose_name = 'Npc Character'
        verbose_name_plural = 'Npc Characters'

    def __str__(self):
        return f'NpcCharacter: {self.id}'
