# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class NpcCorporation(models.Model):
    id = models.BigIntegerField(primary_key=True)
    ceo_id = models.IntegerField(default=None, null=True)
    deleted = models.BooleanField()
    description = models.JSONField(default=dict, null=True)
    extent = models.TextField()
    has_player_personnel_manager = models.BooleanField()
    initial_price = models.IntegerField()
    member_limit = models.IntegerField()
    min_security = models.DecimalField(max_digits=50, decimal_places=30)
    minimum_join_standing = models.IntegerField()
    name = models.JSONField()
    send_char_termination_message = models.BooleanField()
    shares = models.BigIntegerField()
    size = models.TextField()
    station_id = models.IntegerField(default=None, null=True)
    tax_rate = models.DecimalField(max_digits=50, decimal_places=30)
    ticker_name = models.TextField()
    unique_name = models.BooleanField()
    allowed_member_races = models.JSONField(default=list, null=True)
    corporation_trades = models.JSONField(default=list, null=True)
    divisions = models.JSONField(default=list, null=True)
    enemy_id = models.IntegerField(default=None, null=True)
    faction_id = models.IntegerField(default=None, null=True)
    friend_id = models.IntegerField(default=None, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    investors = models.JSONField(default=list, null=True)
    lp_offer_tables = models.JSONField(default=list, null=True)
    main_activity_id = models.IntegerField(default=None, null=True)
    race_id = models.IntegerField(default=None, null=True)
    size_factor = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    solar_system_id = models.IntegerField(default=None, null=True)
    secondary_activity_id = models.IntegerField(default=None, null=True)
    exchange_rates = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Npc Corporation'
        verbose_name_plural = 'Npc Corporations'

    def __str__(self):
        return f'NpcCorporation: {self.id}'
