# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class PlanetSchematic(models.Model):
    cycle_time = models.IntegerField()
    name_id = models.JSONField()
    pins = models.JSONField()
    types = models.JSONField()
