# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class PlanetSchematic(models.Model):
    id = models.BigIntegerField(primary_key=True)
    cycle_time = models.IntegerField()
    name = models.JSONField()
    pins = models.JSONField()
    types = models.JSONField()

    class Meta:
        verbose_name = 'Planet Schematic'
        verbose_name_plural = 'Planet Schematics'

    def __str__(self):
        return f'PlanetSchematic: {self.id}'
