# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class PlanetResource(models.Model):
    id = models.BigIntegerField(primary_key=True)
    power = models.IntegerField(default=None, null=True)
    workforce = models.IntegerField(default=None, null=True)
    cycle_minutes = models.IntegerField(default=None, null=True)
    harvest_silo_max = models.IntegerField(default=None, null=True)
    maturation_cycle_minutes = models.IntegerField(default=None, null=True)
    maturation_percent = models.IntegerField(default=None, null=True)
    mature_silo_max = models.IntegerField(default=None, null=True)
    reagent_harvest_amount = models.IntegerField(default=None, null=True)
    reagent_type_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Planet Resource'
        verbose_name_plural = 'Planet Resources'

    def __str__(self):
        return f'PlanetResource: {self.id}'
