# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Race(models.Model):
    id = models.BigIntegerField(primary_key=True)
    description = models.JSONField(default=dict, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    name = models.JSONField()
    ship_type_id = models.IntegerField(default=None, null=True)
    skills = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Race'
        verbose_name_plural = 'Races'

    def __str__(self):
        return f'Race: {self.id}'
