# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class Race(models.Model):
    description_id = models.JSONField(default=dict, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    name_id = models.JSONField()
    ship_type_id = models.IntegerField(default=None, null=True)
    skills = models.JSONField(default=dict, null=True)
