# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Region(models.Model):
    center = models.JSONField()
    description_id = models.IntegerField(default=None, null=True)
    faction_id = models.IntegerField(default=None, null=True)
    max = models.JSONField()
    min = models.JSONField()
    name_id = models.IntegerField()
    nebula = models.IntegerField()
    region_id = models.IntegerField(primary_key=True)
    wormhole_class_id = models.IntegerField(default=None, null=True)
