# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class SkinLicense(models.Model):
    id = models.BigIntegerField(primary_key=True)
    duration = models.IntegerField()
    license_type_id = models.IntegerField()
    skin_id = models.IntegerField()
    is_single_use = models.BooleanField(default=False, null=True)

    class Meta:
        verbose_name = 'Skin License'
        verbose_name_plural = 'Skin Licenses'

    def __str__(self):
        return f'SkinLicense: {self.id}'
