# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Skin(models.Model):
    id = models.BigIntegerField(primary_key=True)
    allow_ccpdevs = models.BooleanField()
    internal_name = models.TextField()
    skin_material_id = models.IntegerField()
    types = models.JSONField()
    visible_serenity = models.BooleanField()
    visible_tranquility = models.BooleanField()
    is_structure_skin = models.BooleanField(default=False, null=True)
    skin_description = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Skin'
        verbose_name_plural = 'Skins'

    def __str__(self):
        return f'Skin: {self.id}'
