# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class SkinMaterial(models.Model):
    id = models.BigIntegerField(primary_key=True)
    display_name = models.JSONField(default=dict, null=True)
    material_set_id = models.IntegerField()

    class Meta:
        verbose_name = 'Skin Material'
        verbose_name_plural = 'Skin Materials'

    def __str__(self):
        return f'SkinMaterial: {self.id}'
