# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class SkinMaterial(models.Model):
    display_name_id = models.IntegerField()
    material_set_id = models.IntegerField()
    skin_material_id = models.IntegerField()
