# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class SkinLicense(models.Model):
    duration = models.IntegerField()
    license_type_id = models.IntegerField()
    skin_id = models.IntegerField()
    is_single_use = models.BooleanField(default=False, null=True)
