# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class SovereigntyUpgrade(models.Model):
    fuel_hourly_upkeep = models.IntegerField(default=None, null=True)
    fuel_startup_cost = models.IntegerField(default=None, null=True)
    fuel_type_id = models.IntegerField(default=None, null=True)
    mutually_exclusive_group = models.TextField()
    power_allocation = models.IntegerField()
    workforce_allocation = models.IntegerField()
