# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class SovereigntyUpgrade(models.Model):
    id = models.BigIntegerField(primary_key=True)
    fuel_hourly_upkeep = models.IntegerField(default=None, null=True)
    fuel_startup_cost = models.IntegerField(default=None, null=True)
    fuel_type_id = models.IntegerField(default=None, null=True)
    mutually_exclusive_group = models.TextField()
    power_allocation = models.IntegerField()
    workforce_allocation = models.IntegerField()

    class Meta:
        verbose_name = 'Sovereignty Upgrade'
        verbose_name_plural = 'Sovereignty Upgrades'

    def __str__(self):
        return f'SovereigntyUpgrade: {self.id}'
