# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class Star(models.Model):
    id = models.IntegerField(primary_key=True)
    radius = models.BigIntegerField()
    statistics = models.JSONField()
    type_id = models.IntegerField()
