# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class Stargate(models.Model):
    destination = models.IntegerField()
    position = models.JSONField()
    type_id = models.IntegerField()
