# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class StationOperation(models.Model):
    activity_id = models.IntegerField()
    border = models.FloatField()
    corridor = models.FloatField()
    description_id = models.JSONField(default=dict, null=True)
    fringe = models.FloatField()
    hub = models.FloatField()
    manufacturing_factor = models.FloatField()
    operation_name_id = models.JSONField()
    ratio = models.FloatField()
    research_factor = models.FloatField()
    services = models.JSONField()
    station_types = models.JSONField(default=dict, null=True)
