# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class StationOperation(models.Model):
    id = models.BigIntegerField(primary_key=True)
    activity_id = models.IntegerField()
    border = models.DecimalField(max_digits=50, decimal_places=30)
    corridor = models.DecimalField(max_digits=50, decimal_places=30)
    description = models.JSONField(default=dict, null=True)
    fringe = models.DecimalField(max_digits=50, decimal_places=30)
    hub = models.DecimalField(max_digits=50, decimal_places=30)
    manufacturing_factor = models.DecimalField(max_digits=50, decimal_places=30)
    operation_name = models.JSONField()
    ratio = models.DecimalField(max_digits=50, decimal_places=30)
    research_factor = models.DecimalField(max_digits=50, decimal_places=30)
    services = models.JSONField()
    station_types = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Station Operation'
        verbose_name_plural = 'Station Operations'

    def __str__(self):
        return f'StationOperation: {self.id}'
