# Automatically generated by sde_gen_models management command
# Last Generate: September 23, 2025

from django.db import models


class StationService(models.Model):
    service_name_id = models.JSONField()
    description_id = models.JSONField(default=dict, null=True)
