# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class StationService(models.Model):
    id = models.BigIntegerField(primary_key=True)
    service_name = models.JSONField()
    description = models.JSONField(default=dict, null=True)

    class Meta:
        verbose_name = 'Station Service'
        verbose_name_plural = 'Station Services'

    def __str__(self):
        return f'StationService: {self.id}'
