# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class TournamentRuleSet(models.Model):
    banned = models.JSONField()
    maximum_pilots_match = models.IntegerField()
    maximum_points_match = models.IntegerField()
    points = models.JSONField()
    rule_set_id = models.TextField(primary_key=True)
    rule_set_name = models.TextField()
