# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class TypeBonus(models.Model):
    id = models.BigIntegerField(primary_key=True)
    role_bonuses = models.JSONField(default=list, null=True)
    types = models.JSONField(default=list, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    misc_bonuses = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Type Bonus'
        verbose_name_plural = 'Type Bonuses'

    def __str__(self):
        return f'TypeBonus: {self.id}'
