# Automatically generated by sde_gen_models management command
# Last Generate: September 30, 2025

from django.db import models


class TypeMaterial(models.Model):
    materials = models.JSONField()
