# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class TypeMaterial(models.Model):
    id = models.BigIntegerField(primary_key=True)
    materials = models.JSONField()

    class Meta:
        verbose_name = 'Type Material'
        verbose_name_plural = 'Type Materials'

    def __str__(self):
        return f'TypeMaterial: {self.id}'
