# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class TypeDogma(models.Model):
    id = models.BigIntegerField(primary_key=True)
    dogma_attributes = models.JSONField()
    dogma_effects = models.JSONField(default=list, null=True)

    class Meta:
        verbose_name = 'Type Dogma'
        verbose_name_plural = 'Type Dogmas'

    def __str__(self):
        return f'TypeDogma: {self.id}'
