# Automatically generated by sde_gen_models management command
# Last Generate: October 4, 2025

from django.db import models


class Types(models.Model):
    id = models.BigIntegerField(primary_key=True)
    group_id = models.IntegerField()
    mass = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    name = models.JSONField()
    portion_size = models.IntegerField()
    published = models.BooleanField()
    volume = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    radius = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    description = models.JSONField(default=dict, null=True)
    graphic_id = models.IntegerField(default=None, null=True)
    sound_id = models.IntegerField(default=None, null=True)
    icon_id = models.IntegerField(default=None, null=True)
    race_id = models.IntegerField(default=None, null=True)
    base_price = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    market_group_id = models.IntegerField(default=None, null=True)
    capacity = models.DecimalField(
        default=None, null=True, max_digits=50, decimal_places=30
    )
    meta_group_id = models.IntegerField(default=None, null=True)
    variation_parent_type_id = models.IntegerField(default=None, null=True)
    faction_id = models.IntegerField(default=None, null=True)

    class Meta:
        verbose_name = 'Types'
        verbose_name_plural = 'Typeses'

    def __str__(self):
        return f'Types: {self.id}'
