# Automatically generated by sde_gen_models management command
# Last Generate: September 8, 2025

from django.db import models


class UniverseLookup(models.Model):
    region_id = models.IntegerField()
    constellation_id = models.IntegerField()
    solar_system_id = models.IntegerField()
    planet_id = models.IntegerField(null=True)
    moons = models.JSONField(default=list, null=True)
    asteroid_belts = models.JSONField(default=list, null=True)

    class Meta:
        unique_together = [
            'region_id',
            'constellation_id',
            'solar_system_id',
            'planet_id',
        ]
        indexes = [
            models.Index(fields=['region_id']),
            models.Index(fields=['constellation_id']),
            models.Index(fields=['solar_system_id']),
            models.Index(fields=['planet_id']),
            models.Index(fields=['moons']),
            models.Index(fields=['asteroid_belts']),
        ]
