# Generated by Django 5.2.6 on 2025-09-25 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('character_name', models.CharField(db_index=True, max_length=100)),
                (
                    'token_type',
                    models.CharField(
                        choices=[
                            ('character', 'Character'),
                            ('corporation', 'Corporation'),
                        ],
                        db_index=True,
                        default='character',
                        max_length=50,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(editable=False, max_length=255)),
                ('refresh_token', models.CharField(editable=False, max_length=255)),
                (
                    'character_owner_hash',
                    models.CharField(db_index=True, max_length=255),
                ),
                ('scopes', models.ManyToManyField(to='esi.scope')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CallbackRedirect',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=128)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                (
                    'token',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='esi.token',
                    ),
                ),
            ],
        ),
    ]
