# Generated by Django 5.2.6 on 2025-09-26 03:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('esi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(editable=False),
        ),
    ]
