# Generated by Django 5.2.6 on 2025-09-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation')], db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
