# Generated by Django 5.2.6 on 2025-09-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0002_token_token_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackredirect',
            name='scopes',
        ),
    ]
