name: Build and Push Prod Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'docker/prod/Dockerfile'
      - 'apps/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docker-prod-ghcr.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}:prod-${{ github.sha }}
      DOCKERFILE: docker/prod/Dockerfile
      CONTEXT: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache uv wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-cache-${{ runner.os }}-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:prod-${{ github.sha }}
            ghcr.io/${{ github.repository }}:prod-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

